# Generated by Django 3.2.7 on 2021-09-10 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('operation', models.CharField(max_length=32)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(default=datetime.datetime(3000, 12, 31, 23, 59, 59, 999999, tzinfo=utc))),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keephistory.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
